[build]
builder = "NIXPACKS"
watchPatterns = ["**/*.py", "**/*.tsx", "**/*.ts", "**/*.jsx", "**/*.js"]

[deploy]
startCommand = "gunicorn app:app --timeout 300 --workers 2 --threads 2 --preload"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
